"""
=====================
Drift Reporter Module
=====================
Generates structured drift reports and stores them in AWS (S3 + DynamoDB).

Report formats:
- **JSON**: Machine-readable report for downstream consumers (OPA, PR generator)
- **Markdown**: Human-readable summary for notifications and PR bodies

Storage:
- **S3**: Full JSON and Markdown reports stored per scan
- **DynamoDB**: Metadata record per scan for querying drift history
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any

import boto3
from botocore.exceptions import ClientError
from jinja2 import Template

from classifier import DriftClassification, DriftSeverity, get_severity_summary

logger = logging.getLogger(__name__)


# =================================
# Markdown Report Template (Jinja2)
# =================================

MARKDOWN_REPORT_TEMPLATE = """

# Infrastructure Drift Report

**Scan ID:** {{ scan_id }}
**Timestamp:** {{ timestamp }}
**Environment:** {{ environment }}
**Region:** {{ region }}

---

## Summary

| Metric | Value |
|--------|-------|
| Total Drifted Resources | {{ summary.total }} |
| Critical | {{ summary.critical }} |
| Functional | {{ summary.functional }} |
| Cosmetic | {{ summary.cosmetic }} |
| Compliance Score | {{ compliance_score }}/100 |

{% if summary.critical > 0 %}
> **CRITICAL DRIFT DETECTED** — Immediate attention required!
{% endif %}

---

## Drifted Resources

{% for drift in drifts %}
### {{ loop.index }}. {{ drift.resource_address }}

| Property | Value |
|----------|-------|
| Resource Type | `{{ drift.resource_type }}` |
| Severity | **{{ drift.severity | upper }}** |
| Action | {{ drift.action }} |
| Reason | {{ drift.reason }} |

{% if drift.changed_attributes %}
**Changed Attributes:** `{{ drift.changed_attributes | join("`, `") }}`
{% endif %}

{% if drift.before or drift.after %}
<details>
<summary>View Changes</summary>

**Before:**
```json
{{ drift.before | tojson(indent=2) }}
```

**After:**
```json
{{ drift.after | tojson(indent=2) }}
```

</details>
{% endif %}

---

{% endfor %}

{% if not drifts %}
**No drift detected!** Infrastructure matches Terraform state.
{% endif %}

## Resource Type Breakdown

| Resource Type | Count |
|---------------|-------|
{% for rtype, count in summary.by_resource_type.items() %}
| `{{ rtype }}` | {{ count }} |
{% endfor %}

---

*Report generated by Infrastructure Drift Detection Engine*
"""


class DriftReporter:
    """
    Generates drift reports and stores them in S3 and DynamoDB.

    Usage:
        reporter = DriftReporter(
            s3_bucket="my-drift-reports",
            dynamodb_table="drift-history",
            environment="dev",
            region="us-east-1"
        )
        report = reporter.generate_report(scan_id, classifications)
        reporter.store_report(report)
    """

    def __init__(
        self,
        s3_bucket: str | None = None,
        dynamodb_table: str | None = None,
        environment: str = "dev",
        region: str = "us-east-1",
    ):
        """
        Initialize the reporter.

        Args:
            s3_bucket: S3 bucket name for storing reports
            dynamodb_table: DynamoDB table name for drift history
            environment: Environment name (dev, staging, prod)
            region: AWS region
        """
        self.s3_bucket = s3_bucket or os.environ.get(
            "DRIFT_REPORTS_BUCKET", "drift-engine-drift-reports"
        )
        self.dynamodb_table = dynamodb_table or os.environ.get(
            "DRIFT_HISTORY_TABLE", "drift-engine-drift-history"
        )
        self.environment = environment
        self.region = region

        # Initialize AWS clients (lazy — only created when needed)
        self._s3_client = None
        self._dynamodb_resource = None

    @property
    def s3(self):
        """Lazy S3 client initialization."""
        if self._s3_client is None:
            self._s3_client = boto3.client("s3", region_name=self.region)
        return self._s3_client

    @property
    def dynamodb(self):
        """Lazy DynamoDB resource initialization."""
        if self._dynamodb_resource is None:
            self._dynamodb_resource = boto3.resource(
                "dynamodb", region_name=self.region
            )
        return self._dynamodb_resource

    def generate_report(
        self,
        scan_id: str,
        classifications: list[DriftClassification],
        metadata: dict[str, Any] | None = None,
    ) -> dict:
        """
        Generate a complete drift report from classification results.

        Args:
            scan_id: Unique identifier for this scan
            classifications: List of drift classifications
            metadata: Optional additional metadata to include

        Returns:
            Report dictionary containing JSON data, Markdown, and metadata.
        """
        timestamp = datetime.now(timezone.utc).isoformat()
        summary = get_severity_summary(classifications)
        compliance_score = self._calculate_compliance_score(summary)

        # Build the JSON report
        json_report = {
            "scan_id": scan_id,
            "timestamp": timestamp,
            "environment": self.environment,
            "region": self.region,
            "summary": summary,
            "compliance_score": compliance_score,
            "drifts": [c.to_dict() for c in classifications],
            "metadata": metadata or {},
        }

        # Render the Markdown report
        template = Template(MARKDOWN_REPORT_TEMPLATE)
        markdown_report = template.render(
            scan_id=scan_id,
            timestamp=timestamp,
            environment=self.environment,
            region=self.region,
            summary=summary,
            compliance_score=compliance_score,
            drifts=[c.to_dict() for c in classifications],
        )

        return {
            "json": json_report,
            "markdown": markdown_report,
            "scan_id": scan_id,
            "timestamp": timestamp,
            "summary": summary,
            "compliance_score": compliance_score,
        }

    def store_report(self, report: dict) -> dict:
        """
        Store the drift report in S3 and DynamoDB.

        Args:
            report: Report dictionary from generate_report()

        Returns:
            Storage result with S3 keys and DynamoDB status.
        """
        scan_id = report["scan_id"]
        timestamp = report["timestamp"]
        date_prefix = timestamp[:10]  # YYYY-MM-DD

        result = {
            "s3_json_key": None,
            "s3_markdown_key": None,
            "dynamodb_status": None,
        }

        # Store JSON report in S3
        try:
            json_key = f"reports/{date_prefix}/{scan_id}/drift-report.json"
            self.s3.put_object(
                Bucket=self.s3_bucket,
                Key=json_key,
                Body=json.dumps(report["json"], indent=2, default=str),
                ContentType="application/json",
                ServerSideEncryption="AES256",
            )
            result["s3_json_key"] = json_key
            logger.info("Stored JSON report: s3://%s/%s", self.s3_bucket, json_key)
        except ClientError as e:
            logger.error("Failed to store JSON report in S3: %s", e)
            raise

        # Store Markdown report in S3
        try:
            md_key = f"reports/{date_prefix}/{scan_id}/drift-report.md"
            self.s3.put_object(
                Bucket=self.s3_bucket,
                Key=md_key,
                Body=report["markdown"],
                ContentType="text/markdown",
                ServerSideEncryption="AES256",
            )
            result["s3_markdown_key"] = md_key
            logger.info("Stored Markdown report: s3://%s/%s", self.s3_bucket, md_key)
        except ClientError as e:
            logger.error("Failed to store Markdown report in S3: %s", e)
            raise

        # Store metadata in DynamoDB
        try:
            table = self.dynamodb.Table(self.dynamodb_table)
            item = {
                "scan_id": scan_id,
                "timestamp": timestamp,
                "environment": self.environment,
                "region": self.region,
                "total_drifts": report["summary"]["total"],
                "critical_count": report["summary"]["critical"],
                "functional_count": report["summary"]["functional"],
                "cosmetic_count": report["summary"]["cosmetic"],
                "compliance_score": report["compliance_score"],
                "s3_json_key": result["s3_json_key"],
                "s3_markdown_key": result["s3_markdown_key"],
                "resource_types": json.dumps(
                    report["summary"].get("by_resource_type", {})
                ),
                "ttl": int(
                    datetime.now(timezone.utc).timestamp() + 90 * 24 * 3600
                ),  # 90-day TTL
            }
            table.put_item(Item=item)
            result["dynamodb_status"] = "success"
            logger.info("Stored drift metadata in DynamoDB: %s", scan_id)
        except ClientError as e:
            logger.error("Failed to store metadata in DynamoDB: %s", e)
            result["dynamodb_status"] = f"error: {str(e)}"

        return result

    def _calculate_compliance_score(self, summary: dict) -> int:
        """
        Calculate a compliance score (0-100) based on drift severity.

        Scoring:
        - Start at 100
        - Each critical drift: -15 points
        - Each functional drift: -5 points
        - Each cosmetic drift: -1 point
        - Minimum score: 0

        Returns:
            Integer compliance score between 0 and 100.
        """
        score = 100
        score -= summary.get("critical", 0) * 15
        score -= summary.get("functional", 0) * 5
        score -= summary.get("cosmetic", 0) * 1
        return max(0, score)

    def generate_local_report(
        self,
        scan_id: str,
        classifications: list[DriftClassification],
        output_dir: str = "./reports",
    ) -> dict:
        """
        Generate and save reports locally (for development/testing).

        Args:
            scan_id: Unique identifier for this scan
            classifications: List of drift classifications
            output_dir: Directory to save reports

        Returns:
            Dict with file paths of generated reports.
        """
        os.makedirs(output_dir, exist_ok=True)

        report = self.generate_report(scan_id, classifications)

        # Save JSON report
        json_path = os.path.join(output_dir, f"{scan_id}-drift-report.json")
        with open(json_path, "w") as f:
            json.dump(report["json"], f, indent=2, default=str)

        # Save Markdown report
        md_path = os.path.join(output_dir, f"{scan_id}-drift-report.md")
        with open(md_path, "w") as f:
            f.write(report["markdown"])

        logger.info("Local reports saved to %s", output_dir)

        return {
            "json_path": json_path,
            "markdown_path": md_path,
            "report": report,
        }
